port: 8080
routes:
  - path: /typicode
    upstream: https://jsonplaceholder.typicode.com
    auth_required: true
  - path: /api/users
    upstream: http://localhost:3001
    auth_required: false
  - path: /api/orders
    upstream: http://localhost:3002
    auth_required: false